// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// blink //
// ----- //

#define blink_wrap_target 0
#define blink_wrap 9
#define blink_pio_version 0

static const uint16_t blink_program_instructions[] = {
            //     .wrap_target
    0x8080, //  0: pull   noblock
    0xa027, //  1: mov    x, osr
    0x0024, //  2: jmp    !x, 4
    0xa041, //  3: mov    y, x
    0xe001, //  4: set    pins, 1
    0xa022, //  5: mov    x, y
    0x0046, //  6: jmp    x--, 6
    0xe000, //  7: set    pins, 0
    0xa022, //  8: mov    x, y
    0x0049, //  9: jmp    x--, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blink_program = {
    .instructions = blink_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = blink_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config blink_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blink_wrap_target, offset + blink_wrap);
    return c;
}

static inline void blink_program_init(PIO pio, uint sm, uint offset, uint pin) {
   pio_sm_config c = blink_program_get_default_config(offset);
   sm_config_set_set_pins(&c, pin, 1);
   pio_gpio_init(pio, pin);
   pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
   pio_sm_init(pio, sm, offset, &c);
}

#endif
